Description:
  VPC Test

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: DEMO-EC2-ASAV

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 172.30.0.0/16

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 172.30.11.0/24

  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 172.30.12.0/24

  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 172.30.21.0/24

  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 172.30.22.0/24

  # myKeyPair: 
  #   Description: Amazon EC2 Key Pair
  #   Type: "AWS::EC2::KeyPair::KeyName"
  #   Default: AA-TEST

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: m4.xlarge
    AllowedValues:
    - m4.large
    - m4.xlarge

Mappings: 
  RegionMap: 
    "us-east-1": 
      AMI: "ami-099b40fb9f6f4f170"
    "us-east-2":
      AMI: "ami-0bc463be2c5563ab0"
    "us-west-1":
      AMI: "ami-0ea17e02065a25ef3"
    "us-west-2":
      AMI: "ami-0bf6af6883b32dd4b"

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 
        Ref: VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: 
            Ref: EnvironmentName



Outputs:
  PublicIp:
    Description: VPC
    Value:
      Ref: VPC
    Export:
      Name: VPC

